services:
  postgres:
    image: postgres:17
    container_name: postgres_db_gestao_de_horas
    restart: always
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: gestao-hrs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
